### ISSUE TITLE
Warning:(27, 18) Unconditional layout inflation from view adapter: Should use View Holder pattern (use recycled view passed into this method as the second parameter) for smoother scrolling

### ISSUE THREAD

**Issue by dieechtenilente** [AhiruSoftwareCompany/coldmirrorapp#10]
"Unconditional layout inflation from view adapter: Should use View Holder pattern (use recycled view passed into this method as the second parameter) for smoother scrolling"

in class QuoteAdapter "View v = inflater.inflate(R.layout.quotes_items, parent, false);"

**Comment by okitec** [comment]
The time is ripe for more development, I presume? :smile:

**Comment by dieechtenilente** [comment]
Ay, sir. But not today. Great things have been achieved today 8)
