### ISSUE TITLE
JOGURTH!!11111!

### ISSUE THREAD

**Issue by okitec** [AhiruSoftwareCompany/coldmirrorapp#12]
u w0t mate pls fix 'Jogurth' its false!!!

its 'Joghurt' u dumb fool

:stuck_out_tongue: 

(including the screenshot)

**Comment by dieechtenilente** [comment]
Immer diese dummen Deutschen mit ihrer doofen Rechtschreibung q_q

**Comment by okitec** [comment]
Man schreibt Joghurt in keiner Sprache mit einem th hinten :P

Der Grund, wieso ich des sag, ist, weil es halt im Screenshot ist und damit sehr sichtbar, jedenfalls für mich.

**Comment by dieechtenilente** [comment]
Ich kann mich erinnern, des mal gefixt zu haben, weil ich mal gemerkt hab, dass des falsch ist, jedoch offensichtlich der fehler nie behoben wurde.
