### ISSUE TITLE
Optimize quote list

### ISSUE THREAD

**Issue by dieechtenilente** [AhiruSoftwareCompany/coldmirrorapp#7]
~Put all quotes in enum~ or add them programmatically from /res/raw/* and sort them

Current code:
```java
Quote[] quoteArray = {
  new Quote("ahahahalustig", "Ahahaha Lustig!"),
  new Quote("boahistdaslustig", "Boah ist das lustig"),
[...]
  new Quote("volldumm", "Ah, voll dumm"),
  new Quote("wasistdeinlieblingstrinken", "Was ist dein Lieblingsgetränk")};
```

**Comment by okitec** [comment]
How exactly would enums improve your code? Does your current solution not work reliably? Your code looks fine, so using an enum would not improve readability either.

**Comment by dieechtenilente** [comment]
@okitec It works, but now I have to add all my hand

**Comment by okitec** [comment]
You have to type it out once anyway. Consider generating Java code automagically by using Awk (heh) and shell scripting. Code generation is fun.

**Comment by dieechtenilente** [comment]
I thought about something like that. I only have to figure out a smooth and nice way to add buttons programmatically and not creating a new one for each quote :)
