### ISSUE TITLE
Performance: Update search results after submitting a string?

### ISSUE THREAD

**Issue by dieechtenilente** [AhiruSoftwareCompany/coldmirrorapp#8]
Maybe, this is too much...

Current Code:
```java
searchField.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
[...]
    @Override
    public boolean onQueryTextChange(String newText) {
      if (newText != "") {
        addQuotesToList(searchField.getQuery().toString());
      }
        return false;
      }
    });
```

**Comment by okitec** [comment]
Regarding performance:

**Golden rule**. Don't optimise.
**Silver rule**. When obviously too slow, measure, don't guess.
**Data structure before code micro-optimisation**. Using more efficient data structures is often far effective than improving a bit of code, unless that piece of code is the absolutely critical bottleneck.

**Comment by dieechtenilente** [comment]
@okitec Well, it depends on how many quotes are filtered. Right now, its fine, but maybe in the future this will be a problem.

**Comment by okitec** [comment]
Then fix it when, *if at all*, the problem appears. Strive for the simplest code unless in dire need.

**Comment by dieechtenilente** [comment]
Hmm, well - closed for now

**Comment by okitec** [comment]
Thank you for heeding my advice. :smile:
